# Generated by Django 4.0.3 on 2022-05-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_product_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='3.JPG', null=True, upload_to=''),
        ),
    ]
